In [1]:
print("hello world!")

hello world!


In [2]:
ODD = {1:'One',3:'Three',5:'Five',7:'Seven',9:'Nine'}

In [3]:
ODD

{1: 'One', 3: 'Three', 5: 'Five', 7: 'Seven', 9: 'Nine'}

In [4]:
ODD.keys()

dict_keys([1, 3, 5, 7, 9])

In [5]:
ODD.values()

dict_values(['One', 'Three', 'Five', 'Seven', 'Nine'])

In [6]:
ODD.items()

dict_items([(1, 'One'), (3, 'Three'), (5, 'Five'), (7, 'Seven'), (9, 'Nine')])

In [7]:
len(ODD)

5

In [8]:
7 in ODD

True

In [9]:
2 in ODD

False

In [10]:
ODD.get(9)

'Nine'

In [11]:
del ODD(9)

SyntaxError: cannot delete function call (1804934045.py, line 1)

In [12]:
del ODD[9]
ODD

{1: 'One', 3: 'Three', 5: 'Five', 7: 'Seven'}

In [16]:
num = int(input("Enter the number of employees whose data to be stored: "))
count = 1
employee = dict()
for count in range (num):
    name = input("Enter the name of the Employee: ")
    salary = int(input("Enter the salary: "))
    employee[name] = salary
print("\n\nEMPLOYEE_NAME\tSALARY")
for k in employee:
    print(k, '\t\t', employee[k])

Enter the number of employees whose data to be stored: 2
Enter the name of the Employee: Jarin
Enter the salary: 10
Enter the name of the Employee: Maruf
Enter the salary: 5


EMPLOYEE_NAME	SALARY
Jarin 		 10
Maruf 		 5


In [18]:
import numpy as np
a = np.array([10,20,30])
a

array([10, 20, 30])

In [19]:
import numpy as np
a = np.array([[10,20,30], [40, 50, 60]])
a

array([[10, 20, 30],
       [40, 50, 60]])

In [22]:
ls = np.linspace(1, 10, 10)
ls

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [24]:
np.zeros([5,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [25]:
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [27]:
a.shape

(2, 3)

In [28]:
a.size

6

In [31]:
np.random.rand(2)

array([0.00218227, 0.52523492])

In [32]:
np.random.rand(5,5)

array([[0.26910745, 0.787884  , 0.94518233, 0.46098224, 0.69440562],
       [0.16796123, 0.64790296, 0.85859454, 0.6481904 , 0.33875137],
       [0.88341997, 0.09867739, 0.12572321, 0.3806584 , 0.83187675],
       [0.6050628 , 0.3435178 , 0.79961786, 0.7637265 , 0.19937891],
       [0.96074535, 0.5206043 , 0.30091353, 0.49109216, 0.84876886]])

In [33]:
a.reshape(2,3)
a

array([[10, 20, 30],
       [40, 50, 60]])

In [34]:
a.reshape(6,2)
a

ValueError: cannot reshape array of size 6 into shape (6,2)

In [35]:
a.reshape(3,2)
a

array([[10, 20, 30],
       [40, 50, 60]])

In [39]:
np.random.randint(1,10)

5